version: "3.2"
services:
  mongo:
    container_name: mongo_container
    image: mongo:5.0
    ports:
      - published: ${DB_PORT:-27017}
        target: 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
  auth:
    build:
      context: services/auth
      dockerfile: Dockerfile
    ports:
      - published: ${APP_PORT:-3000}
        target: 3000
    environment:
      JWT_SECRET: ${JWT_SECRET}
  movies:
    build:
      context: services/movies
      dockerfile: Dockerfile
    ports:
      - published: ${MOVIES_PORT:-4000}
        target: 3000
    environment:
      JWT_SECRET: ${JWT_SECRET}
      MONGO_URI: mongodb://${DB_USER}:${DB_PASS}@mongo:${DB_PORT}
      OMDB_API_KEY: ${OMDB_API_KEY}
    depends_on:
      - mongo