version: "3.2"
services:
  mongo:
    container_name: mongo_container
    image: mongo:5.0
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
    volumes:
      - mongo_container_data:/data/db
  auth:
    build:
      context: services/auth
      dockerfile: Dockerfile
    ports:
      - published: ${APP_PORT:-3000}
        target: 3000
    volumes:
      - .:/app/
    environment:
      JWT_SECRET: ${JWT_SECRET}
  movies:
    build:
      context: services/movies
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    environment:
      JWT_SECRET: ${JWT_SECRET}
      MONGO_URI: mongodb://${DB_USER}:${DB_PASS}@mongo:27017
      OMDB_API_KEY: ${OMDB_API_KEY}

volumes:
  mongo_container_data:
